### ISSUE TITLE
consider adding github action support

### ISSUE THREAD

**Issue by danmarsden** [anayleeloolxp/moodle-block_tb_faq#1]
I see you have previously added travis-ci to this repo but you might want to remove that now that they charge for it and move to github actions:

Some of the tests run by the Moodle.org plugins db can be run via github actions on each commit in your github repo. Enabling this helps you to make sure future changes to your plugin will continue to follow the guidelines.

the short version - grab this file:
https://github.com/moodlehq/moodle-plugin-ci/blob/master/gha.dist.yml
rename it as ci.yml and put into the directory .github/workflows within tyour project eg:
https://github.com/danmarsden/moodle-mod_attendance/blob/main/.github/workflows/ci.yml

then on every commit you make to github it will fire off a request to run the tests and will give you traffic lights beside each commit and generate a report.

**Comment by anayleeloolxp** [comment]
Hello @danmarsden Thanks a lot for suggestion github workflows. I will definitely look into it. And implement it. Really thanks a lot for the suggestion, as yeah travis charges us.
