### ISSUE TITLE
incorrect function name

### ISSUE THREAD

**Issue by danmarsden** [anayleeloolxp/moodle-block_tb_faq#2]
all local functions should be prefixed with the frankenstyle naming convention.

https://github.com/anayleeloolxp/moodle-block_tb_faq/blob/master/locallib.php#L31
should be something like: block_tb_faq_update

more info here:
https://docs.moodle.org/dev/Frankenstyle#Function_names

**Comment by anayleeloolxp** [comment]
Hello @danmarsden Have renamed the function to block_tb_faq_updateconf
