### ISSUE TITLE
styles.css not specific enough

### ISSUE THREAD

**Issue by danmarsden** [anayleeloolxp/moodle-block_tb_faq#3]
in your styles.css you define a number of generic styles that could clash with core moodle code or other locations where simliar names are used. 

Moodle helpfully adds a number of classes to the body tag based on the path that you can use such as:
eg if you are have a file in mod/assign you would see the following class added to the body tag
path-mod-assign
so if you have an item with the class "filething" on the page you would target it like:
```
.path-mod-assign .filething {
   color: red;
}
```

Any content within your block could be targeted using .block_tb_faq but generic tags like "div#faq_box" are not allowed.
ideally it should be :
.block_tb_faq div#faq_box {

Or some other more specific tag that makes sure that the css will only apply to your content and not some other html where a teacher adds something to the site with the same css tag.

Please make sure your css classes in styles.css are specific enough so they cannot clash with other core code.

**Comment by anayleeloolxp** [comment]
Hello @danmarsden have fixed the css. Have used ".block_tb_faq" as prefix for the css inside the plugin,
