### ISSUE TITLE
missing thirdpartylibs.xml file for jquery js

### ISSUE THREAD

**Issue by danmarsden** [anayleeloolxp/moodle-block_tb_faq#4]
When including an external library in your plugin, you must include a thirdpartylibs.xml file that includes the name, location and license of the library.
More information on this is here:
https://docs.moodle.org/dev/Plugin_files#thirdpartylibs.xml
And here:
https://docs.moodle.org/dev/Plugin_with_third_party_libraries

One of the other advantages of using this is that Moodle's codechecker automatically ignores any files included in the location specificed in the thirdpartylibs.xml file.

Please note - this is typically a blocker for approval in the plugins db.

**Comment by danmarsden** [comment]
but... I'm not even sure you actually need jquery in there as Moodle already includes it so it might be easier to remove it and just make your pages use the core Jquery JS instead.

**Comment by anayleeloolxp** [comment]
Hello @danmarsden Have removed the jquery.js file from plugin and have used moodle core jquery js. Thanks for the suggestion.
